### ISSUE TITLE
Remoção de apresentações do `CLI`

### ISSUE THREAD

**Issue by RcleydsonR** [fga-eps-mds/2022-2-MeasureSoftGram-Doc#28]
## Descrição da Issue
Remover parametros ``[--history]`` e ``[--host]`` do comando ``get [measures, metrics, measures, characteristics, subcharacteristic]``.

## Tarefas:
- [ ] Remover opção history no CLI parser do comando get.
- [ ] Remover opção host no CLI parser do comando get.

## Critérios de Aceitação:
- [ ]  Remover parametro [--history] e [--host] do comando ``get metrics --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando  ``get measures --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando  ``get metrics 1 --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando  ``get measures 1 --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando  ``get characteristics  --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando  ``get characteristics 1 --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando ``get subcharacteristic  --history --host``;
- [ ]  Remover parametro [--history] e [--host] do comando ``get subcharacteristic 1 --history --host``;

**Comment by flaviovl** [comment]
A cada alteração na CLI, é necessário empacotar (pip) novamente?

**Comment by Joao-Moura** [comment]
Issue fechada porque essa atividade será diluida nas demais relacionadas ao core/CLI
