### ISSUE TITLE
Implementar dados mockados `FrontEnd`

### ISSUE THREAD

**Issue by RcleydsonR** [fga-eps-mds/2022-2-MeasureSoftGram-Doc#30]
## Descrição da Issue
Criar mocks de organizações, produtos  e repositórios, na base de dados de desenvolvimento,  para que os requisitos de maior valor do produto possam ser desenvolvidos e testados, como, por exemplo, corrigir o equalizador ou criar gráficos tipo radar.

## Tarefas:
- [x] Implementar no mínimo 2 organizações;
- [x] Implementar no mínimo 3 produtos;
- [x] Implementar no mínimo 3 repositórios;

## Critérios de Aceitação:
- [x] Cada organização deve ter mínimo um produto e um repositório;
- [x] Um repositório deve ter cálculos de sub-características, características e SQC;

**Comment by flaviovl** [comment]
Para usar o frontend com esses dados, usar a váriavel de ambiente **.env.development**,  conforme a issue #35. 

![image](https://user-images.githubusercontent.com/31935777/204334782-5a12bcd7-d41b-463d-845a-dc6fd1c78208.png)
---

**Comment by flaviovl** [comment]
* Organizações e produtos adicionados:

![image](https://user-images.githubusercontent.com/31935777/204332174-67337c9e-e603-47e3-91c5-020bbe003ed3.png)

---  

* O produto **VISUALEASY** tem os cálculos de sub-características, características e SQC:

![image](https://user-images.githubusercontent.com/31935777/204333161-e6b41e73-03f8-43ae-9284-91b3d12db193.png)
