### ISSUE TITLE
Aumentar `cobertura de testes` dos repositórios

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/2022-2-MeasureSoftGram-Doc#48]
## Descrição da Issue

Como uma forma de preencher as issues da primeira sprint, e para entender melhor como os códigos funcionam, cada repositório deverá alcançar pelo menos 80% de cobertura em testes unitários

## Tarefas:
- [ ] Cobertura do Frontend em 80%
- [ ] Cobertura da CLI em 80%
- [x] Cobertura do Core em 80%
- [x] Cobertura da Service em 80%

**Comment by italovinicius18** [comment]
Vamos começar a rodar e desenvolver os testes pelo service, pois tanto o cli quanto o frontend utilizam ele.

É possível que em sprints futuras ele não seja necessário para operações na CLI, já que é uma feature que está sendo solicitada (não depender do service).

Além disso, o codecov do core está 92%, enquanto a service está em 0%, por esta razão creio que seja melhor começar por ela.

@IanFPFerreira @francisco1code @Joao-Moura

**Comment by Joao-Moura** [comment]
@italovinicius18 só corrigindo, a service já ta com [85.55%](https://github.com/fga-eps-mds/2022-2-MeasureSoftGram-Service/pull/1#issuecomment-1328295613), é só porque a pipeline lá não foi revisada então o sonar não conseguiu pegar as métricas.

Talvez seja até válido já começar direto pelo front já que é o que tem a menor cobertura, ou talvez pela CLI (não tenho certeza se lá já pegou > 80)

**Comment by IanFPFerreira** [comment]
Fiz um primeiro pull request, adicionando a cobertura de 100% do parse_analysis.

**Comment by italovinicius18** [comment]
Com as alterações feitas no CLI foram implementados os seguintes testes pelos responsáveis pela [US2](https://github.com/fga-eps-mds/2022-2-measuresoftgram-doc/issues/62):

- tests/system/test_extract.py
- test_help.py
- tests/system/test_import.py

- tests/system/test_initialize.py

- tests/unit/test_extract.py

- tests/unit/test_initialize.py

**Comment by Joao-Moura** [comment]
Fechando issue inativa por muito tempo e provavelmente já corrigida com os últimos prs do empacotamento.
