### ISSUE TITLE
Refatorar core para adicionar métodos independentes da service

### ISSUE THREAD

**Issue by RcleydsonR** [fga-eps-mds/2022-2-MeasureSoftGram-Doc#69]
## Descrição da Issue

É necessário fazer a refatoração de métodos da core que fazem chamada a service para utilização desses métodos de maneira independente. Core não deve fazer chamada para a service e sim o contrário, sendo uma restrição arquitetural.

## Tarefas:
- [x] Identificar chamadas à service advindas da camada core
- [x] Adicionar lógica no core que está presente na service, porém, é utilizada no core
- [x] Refazer testes da service (se necessário)
- [x] Melhorar testes da core devido ao código introduzido

**Comment by RcleydsonR** [comment]
![image](https://user-images.githubusercontent.com/74625814/208547820-06408499-7727-4421-8416-339f486a077e.png)

Nessa votação de planning poker ficou definido como valor 8 o trabalho dessa tarefa, ela é a principal para implementação da US2, e talvez a mais trabalhosa entre as demais issues dessa user story

**Comment by Joao-Moura** [comment]
Issue concluída durante o desenvolvimento do empacotamento do init e export.

**Comment by RcleydsonR** [comment]
Retirado o story point para considerar apenas os pontos totais da tarefa "pai"
