### ISSUE TITLE
Realização do `Brainstorm`

### ISSUE THREAD

**Issue by Joao-Moura** [fga-eps-mds/2022-2-MeasureSoftGram-Doc#8]

**Comment by italovinicius18** [comment]
14/11/22 - Brainstorming de Funcionalidades relativo aos usuários Miguel e Gustavo

**Comment by italovinicius18** [comment]
15/11/22 - Brainstorming de Funcionalidades relativo aos usuários Valéria e Paulo

**Comment by Joao-Moura** [comment]
17/11/22 - Novo reunião com os integrantes da equipe para revisão e adição de novos cards
